heroes_counters = {
    "Hulk": ["Iron Man", "Psylocke", "Storm", "Punisher", "Namor", "Thor", "Peni Parker", "Wolverine", "Mantis",
             "Luna Snow", "Winter Soldier", "Adam Warlock"],
    "Groot": ["Punisher", "Hulk", "Venom", "Storm", "Wolverine", "Iron Man", "Winter Soldier", "Hela", "Cloak & Dagger",
              "Captain America", "Thor", "Rocket Racoon", "Luna Snow", "Mantis", "Invisible Woman", "Psylocke",
              "Star-Lord", "Spider-Man"],
    "Thor": ["Peni Parker", "Iron Man", "Storm", "Wolverine", "Punisher", "Star-Lord", "Scarlet Witch", "Mantis",
             "Psylocke", "Winter Soldier", "Luna Snow",
             "Adam Warlock", "Scarlet Witch", "Namor", "Squirrel Girl"],
    "Doctor Strange": ["Wolverine", "Black Panther", "Hulk", "Magik", "Punisher", "Psylocke",
                       "Invisible Woman", "Mantis", "Luna Snow", "Mr. Fantastic","Winter Soldier"],
    "The Thing": ["Groot", "Iron Man", "Squirrel Girl", "Storm", "Hela", "Adam Warlock", "Scarlet Witch", "Moon Knight",
                  "Doctor Strange", "Star-Lord", "Peni Parker", "Punisher", "Psylocke", "Hawkeye",
                  "Black Widow", "Namor", "Human Torch", "Loki", "Jeff", "Rocket Racoon", "Cloak & Dagger"],
    "Venom": ["Wolverine","Punisher", "Storm", "Iron Man", "Winter Soldier", "Peni Parker", "Adam Warlock",
              "Scarlet Witch", "Squirrel Girl", "Namor", "Luna Snow", "Mantis", "The Thing"],
    "Peni Parker": ["Iron Man", "Storm", "Punisher", "Star-Lord", "Doctor Strange", "Namor", "Groot", "Loki",
                    "Winter Soldier", "Hela", "Moon Knight", "Psylocke", "Adam Warlock", "Invisible Woman"],
    "Captain America": ["Groot", "Namor", "Hela", "Storm", "Scarlet Witch", "Loki", "Peni Parker", "Iron Man",
                        "Human Torch", "Jeff", "Rocket Racoon", "Adam Warlock", "Scarlet Witch", "The Thing"],
    "Magneto": ["Storm", "Groot", "Magik", "Loki", "Adam Warlock",
                "Luna Snow", "Mr. Fantastic", "Winter Soldier", "Spider-Man","The Thing"],

    "Punisher": ["Hela", "Hawkeye", "Iron Fist", "Magik", "Cloak & Dagger", "Black Panther", "Storm",
                 "Magneto", "Moon Knight", "Squirrel Girl", "Loki"],
    "Hela": ["Punisher", "Magik", "Doctor Strange", "Luna Snow", "Loki", "Venom", "Captain America", "Black Panther",
             "Invisible Woman", "Rocket Racoon"],
    "Moon Knight": ["Storm", "Black Panther", "Iron Man", "Spider-Man", "Magneto", "Psylocke", "Magik", "Iron Fist",
                    "Venom", "Star-Lord", "Captain America", "Thor", "Hulk"],
    "Iron Man": [
        "Doctor Strange", "Iron Fist", "Rocket Racoon", "Namor", "Star-Lord",
        "Punisher", "Psylocke", "Spider-Man", "Black Widow", "Hela", "Hawkeye", "Adam Warlock", "Mantis", "Luna Snow",
        "Hulk", "Scarlet Witch"
    ],
    "Winter Soldier": ["Psylocke", "Hela", "Hawkeye", "Namor", "Iron Fist"],
    "Psylocke": ["Star-Lord", "Venom", "Invisible Woman", "Namor", "Punisher", "Luna Snow", "Mantis",
                 "Captain America", "Magneto", "Winter Soldier", "Rocket Racoon", "Loki"],
    "Mr. Fantastic": ["Groot", "Storm", "Punisher", "Iron Man", "Hawkeye", "Hela", "Winter Soldier", "Black Widow",
                      "Squirrel Girl", "Mantis", "Luna Snow", "Adam Warlock", "Cloak & Dagger", "Jeff", "Peni Parker",
                      "Scarlet Witch"],
    "Storm": [
        "Doctor Strange", "Punisher", "Hela", "Namor", "Iron Fist", "Psylocke",
        "Black Widow", "Luna Snow", "Rocket Racoon", "Spider-Man", "Star-Lord", "Mantis",
        "Invisible Woman", "Cloak & Dagger", "Hulk", "Scarlet Witch","Winter Soldier"
    ],
    "Black Panther": [
        "The Thing", "Human Torch", "Star-Lord", "Peni Parker", "Iron Man", "Storm", "Namor", "Loki", "Cloak & Dagger",
        "Magneto",
        "Punisher", "Psylocke", "Mantis", "Winter Soldier", "Jeff", "Adam Warlock", "Luna Snow", "Rocket Racoon",
        "Scarlet Witch"
    ],
    "Squirrel Girl": ["Groot", "Captain America", "Spider-Man", "Hawkeye", "Black Panther", "Storm", "Star-Lord",
                      "Iron Man", "Scarlet Witch", "Human Torch", "Magneto", "Hulk"],
    "Spider-Man": ["Namor", "Hela", "Hawkeye", "Luna Snow", "Cloak & Dagger",
                   "Adam Warlock", "Rocket Racoon", "Jeff",
                   "Squirrel Girl", "Peni Parker", "Captain America", "Scarlet Witch", "Winter Soldier","Punisher"],
    "Star-Lord": ["Magneto", "Luna Snow", "Loki", "Doctor Strange", "Hela", "Punisher", "Hawkeye", "Namor", "Mantis",
                  "Invisible Woman", "Hulk", "Scarlet Witch"],
    "Wolverine": ["Peni Parker", "Iron Man", "Namor", "Storm", "Invisible Woman", "Captain America", "Spider-Man",
                  "Mantis", "Luna Snow", "Magneto", "Hela", "Adam Warlock", "Scarlet Witch", "The Thing"],
    "Hawkeye": ["Psylocke", "Groot", "Spider-Man", "Hela", "Doctor Strange", "Black Panther", "Iron Fist",
                "Rocket Racoon", "Loki"],
    "Magik": ["Iron Man", "Namor", "Storm", "Doctor Strange", "Luna Snow", "Peni Parker", "Magneto", "Thor",
              "Winter Soldier", "Adam Warlock", "Cloak & Dagger", "Jeff", "Rocket Racoon", "Scarlet Witch"],
    "Black Widow": ["Psylocke", "Magik", "Black Panther", "Doctor Strange", "Venom", "Captain America",
                    "Scarlet Witch"],
    "Scarlet Witch": ["Punisher", "Doctor Strange", "Hawkeye", "Hela", "Peni Parker", "Mantis",
                      "Luna Snow"],
    "Namor": ["Moon Knight", "Hela", "Hawkeye", "Venom", "Magneto", "Doctor Strange", "Punisher", "Winter Soldier",
              "Loki", "Cloak & Dagger", "Adam Warlock"],
    "Iron Fist": ["Namor", "Captain America", "Invisible Woman", "Rocket Racoon", "Loki", "Moon Knight", "Storm",
                  "Luna Snow", "Winter Soldier", "Punisher", "Mantis", "Hulk", "Peni Parker", "Scarlet Witch",
                  "Squirrel Girl", "Magik", "Hela", "Adam Warlock"],
    "Human Torch": ["Hela", "Hawkeye", "Punisher", "Psylocke", "Spider-Man", "Luna Snow", "Hulk", "Scarlet Witch"],

    "Loki": ["Moon Knight", "Iron Man", "Punisher", "Winter Soldier", "Wolverine", "Adam Warlock", "Spider-Man",
             "Mr. Fantastic", "Captain America", "Thor", "The Thing", "Storm", "Hela", "Jeff","Moon Knight"],
    "Cloak & Dagger": ["Magneto", "Magik", "Hela", "Hawkeye", "Psylocke", "Wolverine", "Jeff", "Squirrel Girl",
                       "Moon Knight", "Rocket Racoon"],
    "Jeff": ["Iron Man", "Storm", "Spider-Man", "Psylocke", "Peni Parker", "Squirrel Girl", "Magneto", "Hela",
             "Cloak & Dagger", "Iron Fist", "Luna Snow", "Mantis", "The Thing", "Namor"],
    "Mantis": ["Iron Man", "Punisher", "Iron Fist", "Captain America", "Psylocke", "Jeff", "Magneto", "Hela", "Magik",
               "Black Panther", "Moon Knight", "Squirrel Girl", "The Thing", "Wolverine", "Star-Lord", "Rocket Racoon","Storm"],
    "Luna Snow": ["Iron Man", "Punisher", "Psylocke", "Scarlet Witch", "Captain America", "Loki", "Magneto",
                  "The Thing", "Magik", "Black Panther", "Mr. Fantastic", "Moon Knight", "Venom", "Thor",
                  "Hulk", "Rocket Racoon","Storm"],
    "Rocket Racoon": ["Star-Lord", "Black Panther", "Iron Man", "Psylocke", "Venom", "Magneto", "Iron Fist",
                      "Captain America", "Punisher", "Wolverine","Storm"],
    "Invisible Woman": ["Punisher", "Moon Knight", "Squirrel Girl", "Magik", "Spider-Man", "Jeff", "Iron Man",
                        "Magneto", "Namor", "The Thing", "Rocket Racoon", "Mr. Fantastic","Storm","Black Panther"],
    "Adam Warlock": [ "Black Panther", "Magneto", "Doctor Strange", "Hela", "Black Widow",
                     "Winter Soldier", "Squirrel Girl","Storm"],
}

heroes = [
    "Hulk", "Groot", "Thor", "Doctor Strange", "The Thing", "Venom", "Peni Parker", "Captain America", "Magneto",
    "Punisher", "Hela", "Moon Knight",
    "Iron Man", "Winter Soldier", "Psylocke", "Mr. Fantastic", "Storm", "Black Panther", "Squirrel Girl",
    "Spider-Man", "Star-Lord", "Wolverine", "Hawkeye", "Magik", "Black Widow", "Scarlet Witch", "Namor",
    "Iron Fist", "Human Torch", "Loki", "Cloak & Dagger", "Jeff", "Mantis", "Luna Snow",
    "Rocket Racoon", "Invisible Woman", "Adam Warlock",
]

futures = ["Quicksilver", "Doctor Doom", "Cyclops", "Jean Grey", "Rogue", "Gambit", "Beast", "Iceman", "Colossus",
           "Nightcrawler",
           "Shadowcat", "Cable", "Deadpool", "Emma Frost", "Juggernaut", "Mystique", "Sabretooth",
           "Silver Surfer", "Vision", ]

heroes_compositions = {
    "Hulk": [],
    "Groot": ["Invisible Woman", "Jeff", "Cloak & Dagger", "Luna Snow"],
    "Thor": ["Hela", "Doctor Strange", "Magneto"],
    "Doctor Strange": ["Hulk"],
    "The Thing": ["Invisible Woman", "Mr. Fantastic", "Captain America", "Thor", "Hulk", "Venom", "Doctor Strange",
                  "Cloak & Dagger", "Jeff", "Magneto"],
    "Venom": [],
    "Peni Parker": ["Venom", "Groot", "Luna Snow", "Invisible Woman", "Cloak & Dagger"],
    "Captain America": ["Thor"],
    "Magneto": ["Scarlet Witch"],

    "Punisher": ["Doctor Strange", "Rocket Racoon"],
    "Hela": [],
    "Moon Knight": ["Cloak & Dagger"],
    "Iron Man": ["Hulk"],
    "Winter Soldier": ["Rocket Racoon"],
    "Psylocke": ["Doctor Strange", "Magik"],
    "Mr. Fantastic": ["Invisible Woman", "Captain America", "Thor", "Hulk", "Venom", "Doctor Strange", "The Thing"],
    "Storm": ["Thor", "Invisible Woman", "Human Torch"],
    "Black Panther": ["Magik"],
    "Squirrel Girl": ["Spider-Man"],
    "Spider-Man": ["Venom"],
    "Star-Lord": ["Adam Warlock"],
    "Wolverine": ["Hulk", "The Thing"],
    "Hawkeye": [],
    "Magik": [],
    "Black Widow": ["Hawkeye"],
    "Scarlet Witch": ["Doctor Strange"],
    "Namor": ["Luna Snow"],
    "Iron Fist": [],
    "Human Torch": ["Invisible Woman"],

    "Loki": ["Hela"],
    "Cloak & Dagger": [],
    "Jeff": ["Luna Snow","Groot"],
    "Mantis": ["Captain America", "Adam Warlock"],
    "Luna Snow": ["Hulk", "The Thing", "Groot", "Iron Fist"],
    "Rocket Racoon": ["Captain America"],
    "Invisible Woman": [],
    "Adam Warlock": [],
}

hero_roles = {
    "tanks": ["Hulk", "Groot", "Thor", "Doctor Strange", "The Thing", "Venom", "Peni Parker", "Captain America", "Magneto"],
    "attackers": ["Punisher", "Hela", "Moon Knight", "Iron Man", "Winter Soldier", "Psylocke", "Mr. Fantastic", "Storm", 
                  "Black Panther", "Squirrel Girl", "Spider-Man", "Star-Lord", "Wolverine", "Hawkeye", "Magik", 
                  "Black Widow", "Scarlet Witch", "Namor", "Iron Fist", "Human Torch"],
    "supports": ["Loki", "Cloak & Dagger", "Jeff", "Mantis", "Luna Snow", "Rocket Racoon", "Invisible Woman", "Adam Warlock"]
}



# перепроверить нужно : = [
#       "Peni Parker", "Punisher", "Hela",
#     "Iron Man",  "Psylocke", "Mr. Fantastic", "Storm", "Black Panther", "Squirrel Girl",
#      "Star-Lord", "Wolverine", "Hawkeye", "Magik", "Black Widow",  "Namor",
#     "Iron Fist", "Human Torch", "Loki", "Cloak & Dagger", "Jeff", "Mantis", "Luna Snow",
#     "Rocket Racoon", "Invisible Woman", "Adam Warlock",
# ]